config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'pages#home'
  get 'design', to: 'pages#design'
  get 'about', to: 'pages#about'
  get 'cookies', to: 'pages#cookies'

  get 'clothing', to: 'products#clothing'
  get 'clothing/:id', to: 'products#show', as: 'clothing/item'

  get 'shoes', to: 'products#shoes'
  get 'shoes/:id', to: 'products#show', as: 'shoes/item'

  get 'home', to: 'products#home'
  get 'home/:id', to: 'products#show', as: 'home/item'

  resources :products


end

app/models/brand.rb
class Brand < ApplicationRecord
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/color.rb
class Color < ApplicationRecord
end

app/models/country.rb
class Country < ApplicationRecord
end

app/models/main_category.rb
class MainCategory < ApplicationRecord
end

app/models/material.rb
class Material < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :status
end

app/models/pattern.rb
class Pattern < ApplicationRecord
end

app/models/photo.rb
class Photo < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord

  has_many_attached :photos

  belongs_to :brand
  belongs_to :country
  belongs_to :color
  belongs_to :style
  belongs_to :size
  belongs_to :pattern
  belongs_to :segment
  belongs_to :main_category
  belongs_to :category

  has_many :product_materials, dependent: :destroy
  has_many :product_care_instructions, dependent: :destroy
  has_many :product_tags, dependent: :destroy
  has_many :order_products, dependent: :destroy

  has_many :materials, through: :product_materials
  has_many :care_instructions, through: :product_care_instructions
  has_many :tags, through: :product_tags
  has_many :orders, through: :order_products

  validates :name, uniqueness: true, presence: true
  validates :size_id, presence: true
  validates :color_id, presence: true
  validates :pattern_id, presence: true
  validates :product_number, presence: true
  validates :sku, uniqueness: true, presence: true
  validates :description, presence: true
  validates :quantity, presence: true
  validates :brand_id, presence: true
  validates :country_id, presence: true
  validates :style_id, presence: true
  validates :segment_id, presence: true
  validates :main_category_id, presence: true
  validates :category_id, presence: true
  validates :price, presence: true

end

app/models/product_tag.rb
class ProductTag < ApplicationRecord
  belongs_to :product
  belongs_to :tag
end

app/models/role.rb
class Role < ApplicationRecord
end

app/models/segment.rb
class Segment < ApplicationRecord
end

app/models/size.rb
class Size < ApplicationRecord
end

app/models/status.rb
class Status < ApplicationRecord
end

app/models/style.rb
class Style < ApplicationRecord
end

app/models/sub_category.rb
class SubCategory < ApplicationRecord
end

app/models/tag.rb
class Tag < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :orders
  has_many :reviews
end

app/models/user_review.rb
class UserReview < ApplicationRecord
  belongs_to :user
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= title %>
    <link rel="icon"
          type="image/png"
          href="<%= image_path("logo/logo_100x100.png")  %> ">
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/cookie_message' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= render 'shared/footer' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/about.html.erb
<div class="container">
  <h1 class="page-name">About Cilla's Wardrobe</h1>
  <hr>
</div>

app/views/pages/design.html.erb
<div class="container">
  <div class="col-xs-12 col-sm-10 col-sm-offset-1"><!-- col-md-8 col-md-offset-2 -->
    <div class="row">
      <h1 style="font-family: 'LittleLord';">Brand Title Font: 'LittleLord' - Ä Ö Å ä ö å</h1>
      <h1 style="">H tags: 'MicroFLF' - Ä Ö Å ä ö å</h1>
      <p>Content Font: 'MicroFLF' - Here are some special characters in a 'p' tag: Ä, Ö, Å, ä, ö, å, @, #, €, %, &, $, ?, *</p>
    </div>
    <hr>
    <div class="row">
      <ul>
        <li>This is an unordered list</li>
        <li>This is an unordered list</li>
        <li>This is an unordered list</li>
      </ul>
      <ol>
        <li>This is an ordered list</li>
        <li>This is an ordered list</li>
        <li>This is an ordered list</li>
      </ol>
    </div>
    <hr>
    <div class="row">
      <button class="btn btn-primary add-brand-button">Button Primary</button><br>
      <button class="btn btn-success add-brand-button">Button Success</button><br>
      <button class="btn btn-info add-brand-button">Button Info</button><br>
      <button class="btn btn-warning add-brand-button">Button Warning</button><br>
      <button class="btn btn-danger add-brand-button">Button Danger</button><br>

    </div>
    <hr>

    <div class="row">
      <h3>Landing Page Cards</h3>


      <div class="col-xs-12 col-md-4">
        <div class="landing-page-card-outer">
          <div class="landing-page-card-inner">
            <a href="">
              <div class="landing-page-card-image-container" style="background-image: linear-gradient(-25deg, rgba(28, 29, 33, 0.75)0%, rgba(151, 125, 155, 0.35)50%, rgba(28, 29, 33, 0.5)100%), url('https://images.unsplash.com/photo-1509319117193-57bab727e09d?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=634&q=80')">
              </div>
              <div class="landing-page-card-cta">
                Shop Clothing
              </div>
            </a>
          </div>
        </div>
      </div>

      <div class="col-xs-12 col-md-4">
        <div class="landing-page-card-outer">
          <div class="landing-page-card-inner">
            <a href="">
              <div class="landing-page-card-image-container" style="background-image: linear-gradient(-25deg, rgba(28, 29, 33, 0.75)0%, rgba(151, 125, 155, 0.35)50%, rgba(28, 29, 33, 0.5)100%), url('https://urbanclosets.co/wp-content/uploads/2016/11/Logo-Urban-Closets-Kelowna-Shoe-Organizer-ORB-1024x682.jpg')">
              </div>
              <div class="landing-page-card-cta">
                Shop Shoes
              </div>
            </a>
          </div>
        </div>
      </div>

      <div class="col-xs-12 col-md-4">
        <div class="landing-page-card-outer">
          <div class="landing-page-card-inner">
            <a href="">
              <div class="landing-page-card-image-container" style="background-image: linear-gradient(-25deg, rgba(28, 29, 33, 0.75)0%, rgba(151, 125, 155, 0.35)50%, rgba(28, 29, 33, 0.5)100%), url('https://images.unsplash.com/photo-1513519245088-0e12902e5a38?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80')">
              </div>
                <div class="landing-page-card-cta">
                  Shop Home
                </div>
            </a>
          </div>
        </div>
      </div>

    </div>
    <hr>
    <div class="row">
      <h3>Index Page Cards</h3>

      <div class="col-xs-12 col-md-3">
        <div class="index-page-card-outer">
          <div class="index-page-card-inner">
            <a href="">
              <div class="index-page-card-image-container" style="">
              <%= image_tag "sample_product_01.jpg" %>
              </div>
                <div class="index-page-card-brand-name">
                  Lorem Ipsum Brand
                </div>
                <div class="index-page-card-price">
                  XXX SEK
                </div>
            </a>
            <div class="index-page-card-splash">
              <i class="fas fa-thumbs-up"></i>
              <!-- <i class="fas fa-star"></i> -->
            </div>
          </div>
        </div>
      </div>


      <div class="col-xs-12 col-md-3">
        <div class="index-page-card-outer">
          <div class="index-page-card-inner">
            <a href="">
              <div class="index-page-card-image-container" style="">
              <%= image_tag "sample_product_02.jpg" %>
              </div>
                <div class="index-page-card-brand-name">
                  Lorem Ipsum Brand
                </div>
                <div class="index-page-card-price">
                  XXX SEK
                </div>
            </a>
            <div class="index-page-card-splash">
              <i class="fas fa-leaf"></i>
            </div>
          </div>
        </div>
      </div>


      <div class="col-xs-12 col-md-3">
        <div class="index-page-card-outer">
          <div class="index-page-card-inner">
            <a href="">
              <div class="index-page-card-image-container" style="">
              <%= image_tag "sample_product_03.jpg" %>
              </div>
                <div class="index-page-card-brand-name">
                  Lorem Ipsum Brand
                </div>
                <div class="index-page-card-price">
                  XXX SEK
                </div>
            </a>
            <div class="index-page-card-splash">
              <i class="fas fa-gem"></i>
            </div>
          </div>
        </div>
      </div>


      <div class="col-xs-12 col-md-3">
        <div class="index-page-card-outer">
          <div class="index-page-card-inner">
            <a href="">
              <div class="index-page-card-image-container" style="">
              <%= image_tag "sample_product_04.jpg" %>
              </div>
                <div class="index-page-card-brand-name">
                  Lorem Ipsum Brand
                </div>
                <div class="index-page-card-price">
                  XXX SEK
                </div>
            </a>
            <div class="index-page-card-splash">
              <i class="fas fa-recycle"></i>
            </div>
          </div>
        </div>
      </div>




    </div>

    <hr>

  </div>
</div>

app/views/pages/home.html.erb
<div class="hero-banner-outer">
  <div class="landing-page-banner-content">
    <h1>Welcome to Cilla's Waredrobe</h1>
    <h3>the smart way to find fashion &amp; design</h3>

    <div class="container">
      <div class="col-xs-12 col-md-10 col-md-offset-1">
        <div class="row">

          <div class="col-xs-12 col-md-4">
            <div class="landing-page-card-outer">
              <div class="landing-page-card-inner">
                <%= link_to clothing_path do %>
                  <div class="landing-page-card-image-container" style="background-image: linear-gradient(-25deg, rgba(28, 29, 33, 0.75)0%, rgba(151, 125, 155, 0.35)50%, rgba(28, 29, 33, 0.5)100%), url('https://images.unsplash.com/photo-1509319117193-57bab727e09d?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=634&q=80')">
                  </div>
                  <div class="landing-page-card-cta">
                    Shop Clothing
                  </div>
                <% end %>
              </div>
            </div>
          </div>

          <div class="col-xs-12 col-md-4">
            <div class="landing-page-card-outer">
              <div class="landing-page-card-inner">
                <%= link_to shoes_path do %>
                  <div class="landing-page-card-image-container" style="background-image: linear-gradient(-25deg, rgba(28, 29, 33, 0.75)0%, rgba(151, 125, 155, 0.35)50%, rgba(28, 29, 33, 0.5)100%), url('https://urbanclosets.co/wp-content/uploads/2016/11/Logo-Urban-Closets-Kelowna-Shoe-Organizer-ORB-1024x682.jpg')">
                  </div>
                  <div class="landing-page-card-cta">
                    Shop Shoes
                  </div>
                <% end %>
              </div>
            </div>
          </div>

          <div class="col-xs-12 col-md-4">
            <div class="landing-page-card-outer">
              <div class="landing-page-card-inner">
                <%= link_to home_path do %>
                  <div class="landing-page-card-image-container" style="background-image: linear-gradient(-25deg, rgba(28, 29, 33, 0.75)0%, rgba(151, 125, 155, 0.35)50%, rgba(28, 29, 33, 0.5)100%), url('https://images.unsplash.com/photo-1513519245088-0e12902e5a38?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80')">
                  </div>
                    <div class="landing-page-card-cta">
                      Shop Home
                    </div>
                <% end %>
              </div>
            </div>
          </div>

        </div>
      </div>
    </div> <!-- landign page cards -->
  </div>



</div>

app/views/shared/_cookie_message.html.erb
<% if !cookies[:cookie_accept] %>
  <div class="cookie-alert alert-dismissible navbar-fixed-bottom" role="alert">
    <div class="cookie-div-left">
      This page uses cookies for order processing and user experience. You can read more about our cookies&nbsp;<a href="">here</a>.
    </div>
    <div class="cookie-div-right">
      <%= link_to "I accept", cookies_path, class: 'cookie-button btn-success add-brand-button btn-sm' %>
    </div>
  </div>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer-cillas_wardrobe-container">
  <div class="container">
    <div class="col-xs-12 col-md-4">
      <div class="footer-column">
        <ul>
          <li><%= link_to "sell your clothes here" %></li>
        </ul>
      </div>
    </div>
    <div class="col-xs-12 col-md-4">
      <div class="footer-column">
        <ul>
          <li><%= link_to "about", '/about' %></li>
          <li><a href="">terms & conditions</a></li>
          <li><a href="">fashion notes</a></li>
        </ul>
      </div>
    </div>
    <div class="col-xs-12 col-md-4">
      <div class="footer-column">
        <div style="text-align: center;">© <%= Time.now.year %> Cecilia Frick Welch.<br>All rights reserved.</div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-cillas_wardrobe">
  <!-- Logo -->
  <%= link_to root_path do %>
    <div class="navbar-cillas_wardrobe-brand">
      <%= image_tag "logo/logo_200x200.png", height: 50 %>
      <div class="navbar-site-title">CW</div>
    </div>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <div class="dropdown center-it">
      <span class="navbar-cillas_wardrobe-link dropdown-toggle dropdown" data-toggle="dropdown">
        <div>
          <i class="fas fa-list-alt"></i><br>
          products
        </div>
      </span>
      <div class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu ">
        <%# byebug %>
        <li><%= link_to "<i class=\"fas fa-tshirt\"><\/i> Clothing".html_safe, clothing_path, class: "dropdown-item" %></li>
          <li class="dropdown-divider"></li>
        <li><%= link_to "<i class=\"fas fa-shoe-prints\"><\/i> Shoes".html_safe, shoes_path, class: "dropdown-item" %></li>
        <li><%= link_to "<i class=\"fas fa-coffee\"><\/i> Home".html_safe, home_path, class: "dropdown-item" %></li>
          <li><hr></li>
          <li> <%= link_to "<i class=\"fas fa-tshirt\"></i> <em>New Styles</em>".html_safe %> </li>
      </div>
    </div>



    <% if user_signed_in? %>

      <!-- Avatar with dropdown menu -->
      <div class="dropdown center-it">
        <span class="dropdown-toggle" data-toggle="dropdown"><!-- Hi -->
          <div class="navbar-avatar-initials">
            <%= current_user.first_name[0] + current_user.last_name[0] %>
          </div>
        </span>

        <div class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li>
            <%= link_to new_product_path do %>
              <i class="fas fa-plus-circle"></i>  New Product
            <% end %>
          </li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete do %>
              <i class="fas fa-sign-out-alt"></i>  <%= t(".sign_out", default: "Log out") %>
            <% end %>
          </li>
        </div>
      </div>
    <% else %>
    <% # byebug %>
      <% if cookies[:cookie_accept] %>
        <div>
          <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-cillas_wardrobe-link navbar-login-message" %>
        </div>
      <% end %>
    <% end %>




  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <div class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><%= link_to "<i class=\"fas fa-tshirt\"><\/i> Clothing".html_safe, clothing_path %></li>
        <li><%= link_to "<i class=\"fas fa-shoe-prints\"><\/i> Shoes".html_safe, shoes_path %></li>
        <li><%= link_to "<i class=\"fas fa-coffee\"><\/i> Home".html_safe, home_path %></li>
      </div>
    </div>
  </div>
</div>