config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'pages#home'
  get 'design', to: 'pages#design'
  get 'about', to: 'pages#about'
  get 'cookies', to: 'pages#cookies'

  get 'clothing', to: 'products#clothing'
  get 'clothing/:id', to: 'products#show', as: 'clothing/item'

  get 'shoes', to: 'products#shoes'
  get 'shoes/:id', to: 'products#show', as: 'shoes/item'

  get 'home', to: 'products#home'
  get 'home/:id', to: 'products#show', as: 'home/item'

  resources :products


end

app/models/brand.rb
class Brand < ApplicationRecord
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/color.rb
class Color < ApplicationRecord
end

app/models/country.rb
class Country < ApplicationRecord
end

app/models/main_category.rb
class MainCategory < ApplicationRecord
end

app/models/material.rb
class Material < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :status
end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
  belongs_to :order
  belongs_to :product
end

app/models/pattern.rb
class Pattern < ApplicationRecord
end

app/models/photo.rb
class Photo < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord

  has_many_attached :photos

  belongs_to :brand
  belongs_to :country
  belongs_to :color
  belongs_to :style
  belongs_to :size
  belongs_to :pattern
  belongs_to :segment
  belongs_to :main_category
  belongs_to :category

  has_many :product_materials, dependent: :destroy
  has_many :product_care_instructions, dependent: :destroy
  has_many :product_tags, dependent: :destroy
  has_many :order_products, dependent: :destroy

  has_many :materials, through: :product_materials
  has_many :care_instructions, through: :product_care_instructions
  has_many :tags, through: :product_tags
  has_many :orders, through: :order_products

  validates :name, uniqueness: true, presence: true
  validates :size_id, presence: true
  validates :color_id, presence: true
  validates :pattern_id, presence: true
  validates :product_number, presence: true
  validates :sku, uniqueness: true, presence: true
  validates :description, presence: true
  validates :quantity, presence: true
  validates :brand_id, presence: true
  validates :country_id, presence: true
  validates :style_id, presence: true
  validates :segment_id, presence: true
  validates :main_category_id, presence: true
  validates :category_id, presence: true
  validates :price, presence: true

end

app/models/product_tag.rb
class ProductTag < ApplicationRecord
  belongs_to :product
  belongs_to :tag
end

app/models/role.rb
class Role < ApplicationRecord
end

app/models/segment.rb
class Segment < ApplicationRecord
end

app/models/size.rb
class Size < ApplicationRecord
end

app/models/status.rb
class Status < ApplicationRecord
end

app/models/style.rb
class Style < ApplicationRecord
end

app/models/sub_category.rb
class SubCategory < ApplicationRecord
end

app/models/tag.rb
class Tag < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :orders
  has_many :reviews
end

app/models/user_review.rb
class UserReview < ApplicationRecord
  belongs_to :user
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  skip_before_action :authenticate_user!
  before_action :set_all_products
  before_action :set_one_product, only: [:show]
  before_action :refer_url

  def index
    @all_pending_products = @all_products.where(live_status: false);
    @all_live_products = @all_products.where(live_status: true)
  end

  def shoes
    @all_shoe_products = @all_products.where("main_category_id = ? AND live_status = ?", MainCategory.find_by_name("shoes").id, true)

  end

  def clothing
    @all_clothing_products = @all_products.where("main_category_id = ? AND live_status = ?", MainCategory.find_by_name("clothes").id, true)
  end

  def home
    @all_home_products = @all_products.where("main_category_id = ? AND live_status = ?", MainCategory.find_by_name("home").id, true)
  end

  def show
    @product_materials = ProductMaterial.where(product_id: params[:id])
  end

  def new
    @product = Product.new(product_number: make_prod_num, live_status: false)
    @all_sizes = Size.all
    @all_colors = Color.all
    @all_patterns = Pattern.all
    @all_materials = Material.all
  end

  def create
    # byebug
    @all_sizes = Size.all
    @all_colors = Color.all
    @all_patterns = Pattern.all
    @product = Product.new(product_params)
    @all_materials = Material.all
    # @product.user = current_user

    if @product.save
      5.times.with_index do |_, i|
        if params["material_id_0#{(i + 1)}"] != ""
          ProductMaterial.create!(product_id: @product.id,
                                  material_id: params["material_id_0#{(i + 1)}"].to_i,
                                  percent: params["material_percent_0#{(i + 1)}"].to_i)
        else
          break
        end
      end
      redirect_to @product
    else
      render :new
    end
  end

  def edit
    @product = Product.find(params[:id])
    @all_sizes = Size.all
    @all_colors = Color.all
    @all_patterns = Pattern.all
    @all_materials = Material.all
    @product_materials = ProductMaterial.where(product_id: params[:id])
  end

  def update
    @product = Product.find(params[:id])
    # byebug
    @product.update(product_params)

    @all_sizes = Size.all
    @all_colors = Color.all
    @all_patterns = Pattern.all
    @all_materials = Material.all

    if @product.save
      5.times.with_index do |_, i|
        if !params["exist_material_id_0#{(i + 1)}"].nil?
          if (params["exist_material_id_0#{(i + 1)}"]) == "0"
            # byebug
            ProductMaterial.find(params["prod_mat_0#{(i + 1)}"].to_i).destroy
          else
            temp = ProductMaterial.find(params["prod_mat_0#{(i + 1)}"].to_i)
            temp.update!(product_id: @product.id,
                         material_id: params["exist_material_id_0#{(i + 1)}"].to_i,
                         percent: params["exist_material_percent_0#{(i + 1)}"].to_i)
          end
        elsif params["material_id_0#{(i + 1)}"] != ""
          ProductMaterial.create!(product_id: @product.id,
                                  material_id: params["material_id_0#{(i + 1)}"].to_i,
                                  percent: params["material_percent_0#{(i + 1)}"].to_i)
        else
          break
        end
      end
      redirect_to @product
    else
      render :edit
    end

  end




  private

  def product_params
    # byebug
    params.require(:product).permit(:name,
                                    :size_id,
                                    :color_id,
                                    :pattern_id,
                                    :product_number,
                                    :sku,
                                    :live_status,
                                    :description,
                                    :brand_id,
                                    :price,
                                    :quantity,
                                    :style_id,
                                    :segment_id,
                                    :main_category_id,
                                    :category_id,
                                    :country_id,
                                    photos: [])
  end

  def make_prod_num
    t_one = Time.now
    temp = (digi_check(t_one.year) +
            digi_check(t_one.month) +
            digi_check(t_one.day) +
            digi_check(t_one.hour) +
            digi_check(t_one.min) +
            digi_check(t_one.sec) +
            rand(100..999).to_s).scan(/.{1,3}/m).join("-")
  end

  def digi_check(int)
    int.to_s.length == 1 ? "0" + int.to_s : int.to_s[-2..-1]
  end

  def set_one_product
    @product = Product.find(params[:id])
  end

  def set_all_products
    @all_products = Product.all
  end

  def refer_url
    session[:return_to] ||= request.fullpath
  end

end

app/views/products/clothing.html.erb
<div class="container">
  <h1 class="page-name">Clothes in Cilla's Wardrobe</h1>
  <hr>

    <% @all_clothing_products.each do |product| %>
      <div class="col-xs-10 col-xs-offset-1 col-sm-6 col-sm-offset-0 col-md-3">
        <div class="index-page-card-outer">
          <div class="index-page-card-inner">
            <%= link_to clothing_item_path(product) do %>
              <div class="index-page-card-image-container" style="">
              <% if !product.photos[0].nil? %>
                <%= image_tag product.photos[0] %>
              <% else %>
                <%= image_tag "placeholder_prouct_image_01.jpg" %>
              <% end %>
              <!-- <div class="index-page-card-image-bottom-fade"></div> -->
              </div>
              <div class="index-page-card-brand-holder">
                <div class="index-page-card-brand-name">
                  <%= product.brand.name %>
                </div>
              </div>
            <% end %>
              <div class="index-page-card-price">
                <%= product.price %> SEK
              </div>
            <!-- <div class="index-page-card-splash">
              <i class="fas fa-recycle"></i>
            </div> -->
          </div>
        </div>
      </div>
    <% end %>

</div>

app/views/products/edit.html.erb
<div class="container">
  <h1 class="page-name"><span>EDIT</span> <%= @product.name %></h1>
  <hr>
  <div class="col-xs-12 col-sm-8 col-sm-offset-2">
    <div class="row">
      <div class="col-xs-12 col-sm-8 col-sm-offset-2">
        <h6 style="font-weight:bold;">Note: To add new products, you must be certain that the following perameters already exist in the data base:</h6>
        <ul>
          <li>the brand</li>
          <li>the size</li>
          <li>the pattern</li>
          <li>the color</li>
          <li>the style</li>
          <li>the segment, main category and category</li>
        </ul>
        <h6 style="font-weight:bold;">You can add a new <strong>brand</strong> <a href=""><em><u>HERE</u></em></a>. If you need any other new parameters, you must contact <a href=""><em><u>ADMIN</u></em></a> to assist you.</h6>
      </div>
    </div>
    <hr>
    <div id="new-product-form-container">
      <%= simple_form_for @product, html:{class: "new-product-form", id: "edit_product_step_one"} do |f| %>
      <%= f.error_notification %>
      <fieldset class="new-product-input-block"><!-- , remote: true -->
        <legend class="new-product-input-block-title">
          Step One: Product Base
        </legend>
        <div class="form-input">
          <%= f.input :name, class: '' %>
        </div>
        <div class="form-row">
          <div class="col-xs-12 col-sm-4">
            <%= f.association :size, collection: @all_sizes.map{ |s| [s.name, s.id, {'data-code-num' => s.code_num}]}, input_html:{class: 'sku-suffix-component', 'data-code-num' => "test"} %>
          </div>
          <div class="col-xs-12 col-sm-4">
            <%= f.association :color, collection: @all_colors.map{ |s| [s.name, s.id, {'data-code-num' => s.code_num}]}, input_html:{class: 'sku-suffix-component'} %>
          </div>
          <div class="col-xs-12 col-sm-4">
            <%= f.association :pattern, collection: @all_patterns.map{ |s| [s.name, s.id, {'data-code-num' => s.code_num}]}, input_html:{class: 'sku-suffix-component'} %>
          </div>
        </div>
        <div class="form-row">
          <%= f.input :product_number, as: :hidden, input_html:{ value: @product.product_number, class: "sku-suffix-component" } %>

          <%= f.input :sku, as: :hidden, html:{id: "new-product-form-sku-input"} %>  <!--  as: :hidden, -->

          <%#= f.input :live_status, :as => :radio, :input_html => { :value => @product.live_status } %>
          <div class="col-xs-12 col-sm-4">
            <%#= f.input :live_status, label: "Live?" %>
            <%= f.input :live_status,
                        :as => :select,
                        :collection => [['false',false],['true',true]],
                        :include_blank => false,
                        :label => "Live?" %>
          </div>
        </div>
      </fieldset>
      <hr>
      <fieldset class="new-product-input-block"><!-- , remote: true -->
        <legend class="new-product-input-block-title">
          Step Two: Product Details
        </legend>
        <div class="form-input">
          <%= f.input :description, as: :text, input_html:{class: 'new-product-form-description-field'} %>
        </div>
        <div class="form-row">
          <div class="col-xs-12 col-sm-3">
            <%= f.association :brand, class: '' %>
          </div>
          <div class="col-xs-12 col-sm-3">
          <%= f.association :style, input_html:{class: ''} %>
          </div>
          <div class="col-xs-12 col-sm-3">
            <div class="new-product-price-input-outer-wrapper">
              <%= f.input :price, input_html:{step: "10"} %>
              <div class="new-product-form-currency-type">SEK</div>
              </div>
            </div>
          <div class="col-xs-12 col-sm-3">
          <%= f.input :quantity, input_html:{value: 1}%>
          </div>
        </div>
        <div class="form-row">
          <div class="col-xs-12 col-sm-4">
            <%= f.association :segment, class: '' %>
          </div>
          <div class="col-xs-12 col-sm-4">
          <%= f.association :main_category, class: '' %>
          </div>
          <div class="col-xs-12 col-sm-4">
          <%= f.association :category, class: '' %>
          </div>
        </div>
      </fieldset>
      <hr>
      <fieldset class="new-product-input-block"><!-- , remote: true -->
        <legend class="new-product-input-block-title">
          Step Three: Manufacture &amp; Materials
        </legend>
        <h6 align="center">A maximum of 5 material components possible.<br>If you need more contact <a href=""><em><u>ADMIN</u></em></a> to assist you.<br><strong>NOTE:</strong> You can save materials without percentages, if they are missing.</h6>
        <hr>
        <div class="form-row">
          <div class="col-xs-12 col-sm-6 col-sm-offset-3">
            <%= f.association :country, class: '' %>
          </div>
        </div>
        <div class="col-xs-12">
          <% @product_materials.each_with_index do |prod_mat, i| %>
          <% num = i + 1 %>
          <div class="col-xs-4">
            <div class="form-group integer product_quantity">
              <label class="form-control-label integer" for="exist_material_percent_id_0<%= num.to_s %>">Percent</label>
              <input class="form-control numeric integer required" type="number" step="1" name="exist_material_percent_0<%= num.to_s %>" id="exist_material_percent_id_0<%= num.to_s %>" value="<%= prod_mat.percent %>">
            </div>
          </div>
          <div class="col-xs-8">
            <div class="form-group select product_segment">
              <label class="form-control-label select" for="exist_material_id_id_0<%= num.to_s %>">Material Component #<%= num %> </label>
              <select class="form-control select" name="exist_material_id_0<%= num.to_s %>" id="exist_material_id_id_0<%= num.to_s %>" >
                <option value="0"> ¡DELETE this material!</option>
                <% @all_materials.each do |material| %>
                <option <%= prod_mat.material.name == material.name ? "selected=selected" : "" %> value="<%= material.id %>"><%= material.name %></option>
                <% end %>
              </select>
              <input type="hidden" value="<%= prod_mat.id %>" name="prod_mat_0<%= num.to_s %>">
            </div>
          </div>
          <% end %>
          <% (5 - (@product_materials.count)).times.with_index do |_, i| %>
          <% num = (i + 1 + @product_materials.count) %>
          <div class="col-xs-4">
            <div class="form-group integer product_quantity">
              <label class="form-control-label integer" for="material_percent_id_0<%= num.to_s %>">Percent</label>
              <input class="form-control numeric integer required" type="number" step="1" name="material_percent_0<%= num.to_s %>" id="material_percent_id_0<%= num.to_s %>">
            </div>
          </div>
          <div class="col-xs-8">
            <div class="form-group select product_segment">
              <label class="form-control-label select" for="material_id_id_0<%= num.to_s %>">Material Component #<%= num %> </label>
              <select class="form-control select" name="material_id_0<%= num.to_s %>" id="material_id_id_0<%= num.to_s %>">
                <option value=""></option>
                <% @all_materials.each do |material| %>
                <option value="<%= material.id %>"><%= material.name %></option>
                <% end %>
              </select>
            </div>
          </div>
          <% end %>
        </div>
      </fieldset>
    </div>
  </div>

  <div class="col-xs-12 col-sm-10 col-sm-offset-1">
    <hr>
    <div id="new-product-form-container">
      <fieldset class="new-product-input-block">
        <legend class="new-product-input-block-title">
          Current Product Images
        </legend>
        <% if !@product.photos.count.zero? %>
          <div class="product-edit-image-container">
            <% @product.photos.each_with_index do |photo, i| %>
              <div class="product-edit-image-box">
              <div><%= "Photo [#{i + 1}]" %></div>
              <div><%= image_tag photo, class: "product-edit-image-thumb" %></div>

              </div>
            <% end %>
          </div>
        <% else %>
          <h4 align="center"><em>No Photos for the "<%= @product.name.upcase %>"</em></h4>
        <% end %>

    </div>
    <hr>
  </div>
  <div class="col-xs-12 col-sm-8 col-sm-offset-2">
    <div id="new-product-form-container">
      <fieldset class="new-product-input-block">
        <legend class="new-product-input-block-title">
          Step Four: Add Images
        </legend>
        <% if @product.photos.count == 8 %>
          <h5 align="center">Maximum number of photos for the<br><br>"<%= @product.name.upcase %>" already in database.</h5>
        <% else %>
          <div class="row">
            <div class="col-xs-12 col-sm-8 col-sm-offset-2">
              <h6 style="font-weight:bold;">Note: Uploaded/existing photos should follow this order:</h6>
              <ul>
                <li>Photo [1]: Main/Front Image</li>
                <li>Photo [2]: Second/back Image</li>
                <li>Photo [3]: Brand Tag Image</li>
                <li>Photo [4]: Materials/Care Tag Image</li>
                <li>Photo [5]: Detail Image</li>
                <li>Photo [6]: Detail Image</li>
                <li>Photo [7]: Detail Image</li>
                <li>Photo [8]: Detail Image</li>
              </ul>
            </div>
          </div>
          <% ((@product.photos.count + 1)..8).each do |i| %>
            <div class="col-xs-12 col-sm-6">
              <%= f.label "Photo [#{i}]", class: "form-control-label"  %>
              <%= f.file_field :photos, multiple: true, class: "form-control" %>
            </div>
          <% end %>
        <% end %>
      </fieldset>
        <div class="form-row" style="display: flex; justify-content: space-around;">
          <%= f.button :submit, class: 'btn btn-success add-brand-button' %>
        </div>
      <% end %>
    </div>
  </div>

</div>

app/views/products/home.html.erb
<div class="container">
  <h1 class="page-name">Housewares in Cilla's Wardrobe</h1>
  <hr>

    <% @all_home_products.each do |product| %>
      <div class="col-xs-10 col-xs-offset-1 col-sm-6 col-sm-offset-0 col-md-3">
        <div class="index-page-card-outer">
          <div class="index-page-card-inner">
            <%= link_to home_item_path(product) do %>
              <div class="index-page-card-image-container" style="">
              <% if !product.photos[0].nil? %>
                <%= image_tag product.photos[0] %>
              <% else %>
                <%= image_tag "placeholder_prouct_image_01.jpg" %>
              <% end %>
              <div class="index-page-card-image-bottom-fade"></div>
              </div>
              <div class="index-page-card-brand-holder">
                <div class="index-page-card-brand-name">
                  <%= product.brand.name %>
                </div>
              </div>
              <div class="index-page-card-price">
                <%= product.price %> SEK
              </div>
            <% end %>
            <!-- <div class="index-page-card-splash">
              <i class="fas fa-recycle"></i>
            </div> -->
          </div>
        </div>
      </div>
    <% end %>

</div>

app/views/products/index.html.erb
<style>
</style>
<div class="container">
  <h1 class="page-name">Product Master List</h1>
  <hr>

      <div class="col-xs-12">

        <div class="product-master-list-outer">
          <div class="product-master-list-inner">
            <table class="product-master-list-table striped">
              <tr>
                <th></th>
                <th>Name</th>
                <th>Segment</th>
                <th>Main Category</th>
                <th>Category</th>
                <th>Price</th>
                <th>Live</th>
              </tr>
              <% @all_live_products.each do |product| %>
              <tr>
                <td class="product-master-list-thumbnail">
                  <% if !product.photos[0].nil? %>
                    <%= image_tag product.photos[0] %>
                  <% else %>
                    <%= image_tag "placeholder_prouct_image_01.jpg" %>
                  <% end %>
                </td>
                <td>
                  <%= link_to product.name, edit_product_path(product) %>
                </td>
                <td>
                  <%= product.segment.name %>
                </td>
                <td>
                  <%= product.main_category.name %>
                </td>
                <td>
                  <%= product.category.name %>
                </td>
                <td>
                  <%= product.price %>
                </td>
                <td>
                  <%= product.live_status %>
                </td>
              </tr>
              <% end %>
            </table>
          </div>
        </div>

      </div>

</div>

app/views/products/new.html.erb
<div class="container">
  <h1 class="page-name"><span>NEW</span> in Cilla's Wardrobe</h1>
  <hr>
  <div class="col-xs-12 col-sm-8 col-sm-offset-2">
    <div class="row">
      <div class="col-xs-12 col-sm-8 col-sm-offset-2">
        <h6 style="font-weight:bold;">Note: To add new products, you must be certain that the following perameters already exist in the data base:</h6>
        <ul>
          <li>the brand</li>
          <li>the size</li>
          <li>the pattern</li>
          <li>the color</li>
          <li>the style</li>
          <li>the segment, main category and category</li>
        </ul>
        <h6 style="font-weight:bold;">You can add a new <strong>brand</strong> <a href=""><em><u>HERE</u></em></a>. If you need any other new parameters, you must contact <a href=""><em><u>ADMIN</u></em></a> to assist you.</h6>
      </div>
    </div>
    <hr>
    <div id="new-product-form-container">
      <%= simple_form_for @product, html:{class: "new-product-form", id: "new_product_step_one"} do |f| %>
      <%= f.error_notification %>
      <fieldset class="new-product-input-block"><!-- , remote: true -->
        <legend class="new-product-input-block-title">
          Step One: Product Base
        </legend>
        <div class="form-input">
          <%= f.input :name, class: '' %>
        </div>
        <div class="form-row">
          <div class="col-xs-12 col-sm-4">
            <%= f.association :size, collection: @all_sizes.map{ |s| [s.name, s.id, {'data-code-num' => s.code_num}]}, input_html:{class: 'sku-suffix-component', 'data-code-num' => "test"} %>
          </div>
          <div class="col-xs-12 col-sm-4">
            <%= f.association :color, collection: @all_colors.map{ |s| [s.name, s.id, {'data-code-num' => s.code_num}]}, input_html:{class: 'sku-suffix-component'} %>
          </div>
          <div class="col-xs-12 col-sm-4">
            <%= f.association :pattern, collection: @all_patterns.map{ |s| [s.name, s.id, {'data-code-num' => s.code_num}]}, input_html:{class: 'sku-suffix-component'} %>
          </div>
        </div>
        <div class="form-row">
          <%= f.input :product_number, as: :hidden, input_html:{ value: @product.product_number, class: "sku-suffix-component" } %>

          <%= f.input :sku,as: :hidden, html:{id: "new-product-form-sku-input"} %>  <!--  as: :hidden, -->

          <%= f.input :live_status, as: :hidden, :input_html => { :value => @product.live_status } %>
        </div>
      </fieldset>
      <hr>
      <fieldset class="new-product-input-block"><!-- , remote: true -->
        <legend class="new-product-input-block-title">
          Step Two: Product Details
        </legend>
        <div class="form-input">
          <%= f.input :description, as: :text, input_html:{class: 'new-product-form-description-field'} %>
        </div>
        <div class="form-row">
          <div class="col-xs-12 col-sm-3">
            <%= f.association :brand, class: '' %>
          </div>
          <div class="col-xs-12 col-sm-3">
          <%= f.association :style, input_html:{class: ''} %>
          </div>
          <div class="col-xs-12 col-sm-3">
            <div class="new-product-price-input-outer-wrapper">
              <%= f.input :price, input_html:{step: "10"} %>
              <div class="new-product-form-currency-type">SEK</div>
              </div>
            </div>
          <div class="col-xs-12 col-sm-3">
          <%= f.input :quantity, input_html:{value: 1}%>
          </div>
        </div>
        <div class="form-row">
          <div class="col-xs-12 col-sm-4">
            <%= f.association :segment, class: '' %>
          </div>
          <div class="col-xs-12 col-sm-4">
          <%= f.association :main_category, class: '' %>
          </div>
          <div class="col-xs-12 col-sm-4">
          <%= f.association :category, class: '' %>
          </div>
        </div>
      </fieldset>
      <hr>
      <fieldset class="new-product-input-block"><!-- , remote: true -->
        <legend class="new-product-input-block-title">
          Step Three: Manufacture &amp; Materials
        </legend>
        <h6 align="center">A maximum of 5 material components possible.<br>If you need more contact <a href=""><em><u>ADMIN</u></em></a> to assist you.<br><strong>NOTE:</strong> You can save materials without percentages, if they are missing.</h6>
        <hr>
        <div class="form-row">
          <div class="col-xs-12 col-sm-6 col-sm-offset-3">
            <%= f.association :country, class: '' %>
          </div>
        </div>
        <div class="col-xs-12">
          <% 5.times.with_index do |_, i| %>
          <% num = i + 1 %>
          <div class="col-xs-4">
            <div class="form-group integer product_quantity">
              <label class="form-control-label integer" for="material_percent_id_<%= num < 10 ? "0" + num.to_s : num.to_s %>">Percent</label>
              <input class="form-control numeric integer required" type="number" step="1" name="material_percent_<%= num < 10 ? "0" + num.to_s : num.to_s %>" id="material_percent_id_<%= num < 10 ? "0" + num.to_s : num.to_s %>">
            </div>
          </div>
          <div class="col-xs-8">
            <div class="form-group select product_segment">
              <label class="form-control-label select" for="material_id_id_<%= num < 10 ? "0" + num.to_s : num.to_s %>">Material Component #<%= num %> </label>
              <select class="form-control select" name="material_id_<%= num < 10 ? "0" + num.to_s : num.to_s %>" id="material_id_id_<%= num < 10 ? "0" + num.to_s : num.to_s %>">
                <option value=""></option>
                <% @all_materials.each do |material| %>
                <option value="<%= material.id %>"><%= material.name %></option>
                <% end %>
              </select>
            </div>
          </div>
          <% end %>
        </div>
      </fieldset>
      <hr>
      <fieldset class="new-product-input-block">
        <legend class="new-product-input-block-title">
          Step Four: Images
        </legend>
        <div class="row">
          <div class="col-xs-12 col-sm-8 col-sm-offset-2">
            <h6 style="font-weight:bold;">Note: Uploaded/existing photos shold follow this order:</h6>
            <ul>
              <li>Photo [1]: Main/Front Image</li>
              <li>Photo [2]: Second/back Image</li>
              <li>Photo [3]: Brand Tag Image</li>
              <li>Photo [4]: Materials/Care Tag Image</li>
              <li>Photo [5]: Detail Image</li>
              <li>Photo [6]: Detail Image</li>
              <li>Photo [7]: Detail Image</li>
              <li>Photo [8]: Detail Image</li>
            </ul>
          </div>
        </div>
        <% (1..8).each do |i| %>
          <div class="col-xs-12 col-sm-6">
            <%= f.label "Photo [#{i}]", class: "form-control-label"  %>
            <%= f.file_field :photos, multiple: true, class: "form-control" %>
          </div>
        <% end %>
      </fieldset>
        <div class="form-row" style="display: flex; justify-content: space-around;">
          <%= f.button :submit, class: 'btn btn-success add-brand-button' %>
        </div>
      <% end %>

    </div>
  </div>

</div>

app/views/products/shoes.html.erb
<div class="container">
  <h1 class="page-name">Shoes in Cilla's Wardrobe</h1>
  <hr>

    <% @all_shoe_products.each do |product| %>
      <div class="col-xs-10 col-xs-offset-1 col-sm-6 col-sm-offset-0 col-md-3">
        <div class="index-page-card-outer">
          <div class="index-page-card-inner">
            <%= link_to shoes_item_path(product) do %>
              <div class="index-page-card-image-container" style="">
              <% if !product.photos[0].nil? %>
                <%= image_tag product.photos[0] %>
              <% else %>
                <%= image_tag "placeholder_prouct_image_01.jpg" %>
              <% end %>
              <div class="index-page-card-image-bottom-fade"></div>
              </div>
              <div class="index-page-card-brand-holder">
                <div class="index-page-card-brand-name">
                  <%= product.brand.name %>
                </div>
              </div>
              <div class="index-page-card-price">
                <%= product.price - 1 %> SEK
              </div>
            <% end %>
            <!-- <div class="index-page-card-splash">
              <i class="fas fa-recycle"></i>
            </div> -->
          </div>
        </div>
      </div>
    <% end %>

</div>